In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# Reshaping dimensions of array
arr2 = np.array([1,2,3,4,5,6,7])
arr2.reshape(1,7) # as 1 row and 7 elements can be column

array([[1, 2, 3, 4, 5, 6, 7]])

####  [[]] this indicates that the above array is 2-Dimensional

In [8]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr3[0:2,2:]

array([[3, 4],
       [7, 8]])

In [17]:
arr3[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [18]:
arr3[1:,0:2]

array([[ 5,  6],
       [ 9, 10]])